name: unit-test
  
on: [pull_request]
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.9"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Upgrade pip
        run: |  
          python -m pip install --upgrade pip 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Huggingface CLI login
        env: 
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c “from huggingface_hub.hf_api import HfFolder; HfFolder.save_token(${HF_TOKEN})”
      
      - name: Test with pytest  
        run: |  
          pytest tests/